import { Config } from '@/utils/types';

export const InitalConfig = {
  packages: {},
  forms: {}
} as Config;

export const formItems = [
  'complaintName',
  'complaintLegalRepresentative',
  'complaintAddress',
  'complaintSocialCode',
  'defendant1Name',
  'defendant1Mininame',
  'defendant1LegalRepresentative',
  'defendant1LegalRepresentativeDuty',
  'defendant1Address',
  'defendant1Delivery',
  'defendant1Contact',
  'defendant2Name',
  'defendant2Gender',
  'defendant2Idcard',
  'defendant2Nation',
  'defendant2Address',
  'defendant2Delivery',
  'defendant2Contact',
  'total',
  'principal',
  'intrestStartDate',
  'interest',
  'compoundInterest',
  'contract',
  'overdueMonth',
  'counselFee',
  'contractDate',
  'contractNumber',
  'credit',
  'term',
  'loanPurpose',
  'interestMode',
  'interestVariate',
  'repaymentMode',
  'guaranteeContractDate',
  'guaranteeName',
  'guaranteeContract',
  'guaranteeContractNumber',
  'guaranteeTerm',
  'graranteeAmount',
  'mortgageContractDate',
  'mortgageContract',
  'mortgageContractNumber',
  'mortgageHouseOwner',
  'mortgageHouse',
  'mortgageTerm',
  'mortgageAmount',
  'mortgageatioRegistration',
  'registrationDate',
  'jurisdiction'
];
